lite-xl/lite-plugins

- plugins/scale.lua
The scale plugin still used the pre 1.13 path to font files, instead of the DATADIR variable
> Fixed font scale not working

- plugins/lfautoinsert.lua
this pull request creates support for js/css multiline comments to be automatically closed
```javascript
/*
this is a multiline comment
*/
```
> lfautoinsert: add js/css multiline /* comments */

- plugins/language_php.lua
- plugins/language_phps.lua
Worked on improving the PHP language support:
* Use the new mixed syntax color support to allow html, css and js on .php files. 
* Renamed language_php.lua to language_phphtml.lua to better reflect that the file now has html rules (basically language_html but besides css and js also supports &lt;?php ?&gt;, &lt;?= ?&gt; tags with language_phps)
* Introduced language_phps.lua to provide the actual PHP syntax highlighting rules for language_phphtml.lua
* Added some new PHP 8 features like differentiating attributes from comments.
* Allow spaces between functions and parenthesis.
* Colorize static or scope access calls.
* Colorize variables for better readability as other editors do.
* Differentiate array type hinting from array(...) declarations.
* Added support for missing and newer number …
> [language_php] overall improvements.

- plugins/scale.lua
The scale was behaving weird.
It went from 100 -> 110 -> 121 -> 109 -> 98
One had to use ctrl+0 get it back to 100
This is fixed in this commit.
It uses an indicator to change the scale.
> Changed scale behaviour

- README.md
The Plugin "eofnewline" was missing the required `-- lite-xl 1.16` at the start of the file.
I duplicated the original file and added the line. The new file is called `eofnewline-xl.lua`.
A PR was submitted and accepted from the original author.
This commit simply changes the target from `eofnewline.lua` to `eofnewline-xl.lua`.
> Quick Fix: changed target of Plugin eofnewline

- plugins/selectionhighlight.lua
As the title says, this was annoying on my opinion since any minor selection triggered the highlighting of many empty spaces as shown on the screenshots so added the config option to disable it, better explained on the screenshots:
Without the option:
With the option
And highlight works as normal with non-space characters
> [selectionhighlight] added option to not highlight empty spaces.

- plugins/lfautoinsert.lua
Added support of defining elements for specific programming languages by using file patterns and modified default map to use this new feature using some elements only in the languages they should be applied to.
> [lfautoinsert] Added map elements for specific languages

- README.md
- plugins/language_bib.lua
- plugins/pdfview.lua
- plugins/texcompile.lua
Added
1. syntax highlighting for BibTeX files
2. PDF preview for LaTeX files -- tested on Linux and Windows, PDF viewer can be set with environment variable
3. compilation of LaTeX files into PDF -- tested on Linux and Windows, tex compiler has to be set via environment variable (currently only [tectonic](https://tectonic-typesetting.github.io) is supported)
> Added syntax highlighting for BibTeX files, PDF preview for LaTeX files, compilation of LaTeX files into PDF

- plugins/pdfview.lua
pdfview.lua: screen pdffile with "" to handle correctly filenames with spaces (and the like)
> pdfview.lua: bugfix -- handle correctly filenames with spaces

- README.md
Well, not really removing it, just striking it out because we integrated it into lite-xl.
> remove nagbar because it is integrated in lite-xl

- README.md
- plugins/smallclock.lua
Smallclock plugin is a tiny plugin that displays the current time in the status bar.
> added smallclock plugin

- plugins/smallclock.lua
The plugin uses coroutines but did not yield a value, thus the coroutine was called way more often than necessary
Fixed it by simply yielding 1, so it only gets called once per second
> Fixed smallclock plugin eating cpu

- plugins/language_v.lua
`pub` is a keyword, `none` is a literal
> language_v: fix `pub` and `none`

- README.md
- plugins/linenumbers.lua
I decided to write a plugin that would allow not only hiding line numbers, but also making line numbers relative.
Includes the implementation of [hidelinehumbers](https://github.com/lite-xl/lite-plugins/blob/master/plugins/hidelinenumbers.lua) plugin.
However, I'm not sure if the plugin violates compatibility with lite.
> Add  plugin `linenumbers`

- plugins/lfautoinsert.lua
Files that have been just created and not yet saved don't have a filename, so we can't match it to a file ending.
> `lfautoinsert`: Avoid touching new files

- plugins/texcompile.lua
Borrow code from the rxi/console implementation to reliably
run commands on windows. Ideally should be based on the new reproc
library but this has to be done.
Problems of the current implementation:
- the output of the commands is ignored including warning and error messages
- the exit code of the command process is ignored
As a modification from the previous version of the plugin we no longer use
environment variables but we rely on "config" variables.
Partially address Lite XL issue https://github.com/lite-xl/lite-xl/issues/523
> Improve the texcompile plugin to work on windows

- plugins/autowrap.lua
After bringing the last word to a newline, add command to move the cursor to the new line's end. This positions the cursor for continuing at the last character typed.
> Bring cursor to the new line's end after wrapping

- README.md
- plugins/open_ext.lua
This plugin prevents the user from accidentally opening a binary file and break something.
It allows users to open it with other programs (using `xdg-open`).
> add open_ext.lua

- plugins/dragdropselected.lua
- Avoid accidental drags
- Only remove the selection after the drag ends
> `dragdropselected`: Improvements

- plugins/language_make.lua
> `language_make`: Use correct syntax type

- plugins/spellcheck.lua
This entry was missed in #46 which broke the plugin
> Added missing namespace to spellcheck.files config

- plugins/gitstatus.lua
This PR adds the following enhancements to the `gitstatus` plugin:
- Changes to files within submodules are counted.
- Prevents slow git commands from hanging the application.
- If the TreeView supports color highlighting, changed files are highlighted in the tree view.
The TreeView color highlights require this change: https://github.com/lite-xl/lite-xl/pull/684 but if that feature is not present, or TreeView is not available, this plugin will gracefully skip that feature.
Here is a screenshot showing modified files highlighted in the TreeView:
> Git status enhancements

- plugins/openselected.lua
This PR improves the openselected plugin as follows:
- It now works on macOS.
- Whitespace at the ends of selected text are ignored.
- The selected text is escaped before sending to the shell, in case there are spaces, quotes, etc. in it.
- The tool used to open is now configurable.
Parts of this improvement were borrowed from the openfilelocation plugin.
> Improve openselected plugin

- plugins/minimap.lua
This PR fixes a bug in the minimap scrolling behavior. Prior to this change, if you click and drag in the minimap, outside of the small highlighted section, then large sections of text are selected. This was caused by the DocView.on_mouse_pressed function returning a nil value instead of calling the old on_mouse_pressed function.
> Don't select text when dragging in the minimap.

- plugins/minimap.lua
This PR adds the ability to render per-line highlights within the minimap. Other plugins can use this to highlight lines, for example to show git change markers, as seen in this screenshot:
Highlight width can be configured and may appear on the left or right. To make room for the highlight without overlapping the minimap, a gutter_width value can be specified.
> Minimap per-line highlighting

- plugins/minimap.lua
This PR adds a highlight in the minimap which shows the current caret position and the selected region (if any). The colors for these highlights default to colors from the current theme, but can be individually overridden.
> Minimap highlights selection & caret position

- plugins/indentguide.lua
The indentguide plugin does not work with the current main branch of lite-xl. This PR updates it to use the correct API for font sizing.
> Don't use subpixel_scale or get_width_subpixel which no longer exist.
