README.md
works in a similar way to the linter plugin
=> Add formatter plugin

README.md
this implementation is kinda janky but it works
=> Add discord presence plugin

README.md, plugins/restoretabs.lua
Allows for a chrome-like experience with tabs, restoring them with cntrl+shift+t.
=> Added in the restoretabs plugin to restore recently closed tabs.

README.md
It currently doesn't list the feature I was looking for
=> Update autoinsert description

README.md, plugins/autosaveonfocuslost.lua
Automatically saves files that were changed when the main window loses focus
by switching to another application.
=> Add autosaveonfocuslost

README.md, plugins/navigate.lua
Allows navigation from one doc/position to another using alt+left and alt+right.
=> Added navigate plugin

README.md, plugins/regexreplacepreview.lua
Creates a live preview regex replacement. A bit janky, but seems quite useful.
=> Regex Replacement Plugin

README.md, plugins/ephemeraldocviews.lua
Creating a plugin which marks tabs as ephemeral.
=> Added in the ability to have ephemeral tabs.

README.md, plugins/language_po.lua
Support for both po translation files and pot translation template files.
https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html
=> Added language_po

README.md, plugins/minimap.lua
Ripped https://github.com/andsve/lite-plugins/tree/minimap-plugin from their pull request for normal Lite.
It seems to work fine in Lite XL; and I feel like this is something a lot of editors have these days. Definitely shouldn't be a default plugin, but as a plugin in a repo, makes huge sense to me.
=> Minimap Plugin

README.md
I noticed this file in `plugins`. I found no entry on README so I went and created one.
Complements #27
=> add language_tsx to README

plugins/autoinsert.lua, plugins/autosave.lua, plugins/autowrap.lua, plugins/bigclock.lua, plugins/copyfilelocation.lua, plugins/datetimestamps.lua, plugins/lfautoinsert.lua, plugins/minimap.lua, plugins/motiontrail.lua, plugins/openfilelocation.lua, plugins/scalestatus.lua, plugins/selectionhighlight.lua, plugins/spellcheck.lua
If we merge https://github.com/lite-xl/lite-xl/pull/333, we should merge this.
=> Namespaced plugin configs.

plugins/language_sass.lua
I don't have much to say all I did was add 10 characters I hope I didn't spoil anything because I'm not know anything at lua 😅
But the problem has been fixed for me, I hope it works for you
=> add support to .scss fils

README.md
Is this a good time to do a pull request? 
Hoping sth like this would be helpful
=> +lite-xl-vibe plugin with kind of vim bindings

README.md
Added Pony language plugin for the lite and lite-xl editor
=> Feat: Added pony plugin for lite editor

plugins/linenumbers.lua
Updated mod-version and made things 2.0 instead of 2.00.
=> Updated linenumbers.lua to 2.0 mod-version

README.md, plugins/language_R.lua
R is a very primitive language that typically presumes standalone scripting files and does not require anything but an interpreter to run, so it is very neat to write R scratches with lite-xl.
=> Add R scripting language syntax support

plugins/smallclock.lua
=> Update smallclock.lua version

README.md, plugins/statusclock.lua
`statusclock` is a plugin that displays current date and time in the corner of status bar
=> add statusclock plugin

README.md, plugins/language_fstab.lua
Add syntax highlighting for /etc/fstab config files
=> Add syntax highlighting for /etc/fstab files

plugins/indentguide.lua
Reverts lite-xl/lite-plugins#88
=> Revert "Fix: Indentguide plugin crashing lite-xl"

README.md, plugins/smoothcaret.lua
smooth caret animations (for those who aren't motion sick)
=> add smoothcaret.lua

README.md, plugins/opacity.lua
Commit on behalf of @mart-on-windows as mentioned in https://github.com/lite-xl/lite-xl/issues/691
=> Opacity Modification Plugin

README.md, plugins/extend_selection_line.lua
=> Add `extend_selection_line`
